config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  namespace :admin do
    resources :products do
      member do
          patch :toggle_enable_status
          patch :search
      end
    end
    resources :clients do
      member do
        patch :search_client
      end
    end
    resources :invoices do
      member do
        patch :search_product_invoice
      end
    end
  end

  get :add_product, to: "invoices#add_product"
  get 'admin' => 'admin/products#index'
  resources :clients
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :products_imports, only: [:new, :create] #Import Excel
  resources :products
  resources :categories
  resources :catalog
  get :generate_pdf, to: "products#generate_pdf"
  root 'welcome#index'
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :invoices
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < Admin::AdminController
  before_action :set_admin_client, only: [:show, :edit, :update, :destroy]

  # GET /admin/clients
  # GET /admin/clients.json
  def index
    @clients = Client.where(["name ILIKE ?","%#{params[:search_client]}%"])    
  end

  # GET /admin/clients/1
  # GET /admin/clients/1.json
  def show
    @clients = Client.all
  end

  # GET /admin/clients/new
  def new
    @client = Client.new
   
  end

  # GET /admin/clients/1/edit
  def edit
  end

  # POST /admin/clients
  # POST /admin/clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
        format.js
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end
  # DELETE /admin/clients/1
  # DELETE /admin/clients/1.json
  def destroy
    @admin_client.destroy
    respond_to do |format|
      format.html { redirect_to admin_clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_client
      @admin_client = Admin::Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_client_params
      params.fetch(:admin_client, {})
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
  
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @clients = Client.all
  end

  # GET /clients/new
  def new
    @client = Client.new
    respond_to do |f|
      f.html
      f.js 
    end  
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
        format.js
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :nit, :contact, :address, :location, :email, :phone, :cell_phone)
    end
end

app/helpers/admin/clients_helper.rb
module Admin::ClientsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
    def select_clients
        Client.all.pluck(:id, :name, :nit, :contact, :address, :location, :email, :phone, :cell_phone)
    end
end

app/views/admin/clients/_form.html.erb
<%= form_with(model: admin_client, local: true) do |form| %>
  <% if admin_client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_client.errors.count, "error") %> prohibited this admin_client from being saved:</h2>

      <ul>
      <% admin_client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/clients/_sidebar.html.erb
<div class="wrapper">
    <!-- Sidebar Holder -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <%= image_tag("nav/AEI.png", class: "img-responsive", id: "navbar-logo", size: "180x135") %>  
        </div>

        <ul class="list-unstyled components">
            <p class="dashboard">Dashboard</p>
             <li>
                <%= link_to "Inicio", admin_path, class: "text-menu"%>
            </li>
            <li>
                <%= link_to "Productos", admin_path, class: "text-menu"%>
            </li>
            <li>
                <%= link_to "Clientes", admin_clients_path, class: "text-menu"%>        
            </li>
            <li class="active">
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle text-menu">Facturación</a>
                <ul class="collapse list-unstyled" id="homeSubmenu">
                    <li>
                        <%= link_to "Facturas de Venta", admin_invoices_path, class: "text-menu"%>        
                    </li> 
                </ul>
            </li>
              
            <% if current_user%>
            <li>
                <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "text-menu"%>
            </li> 
            <% end %>
        </ul>
    </nav>

    <!-- Page Content Holder -->
    <div id="content">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="navbar-btn">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-align-justify"></i>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <%= render 'clients/view_all'%>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#sidebarCollapse').on('click', function () {
            $('#sidebar').toggleClass('active');
            $(this).toggleClass('active');
        });
    });
</script>

app/views/admin/clients/edit.html.erb
<h1>Editing Admin Client</h1>

<%= render 'form', admin_client: @admin_client %>

<%= link_to 'Show', @admin_client %> |
<%= link_to 'Back', admin_clients_path %>

app/views/admin/clients/new.html.erb
            <%= form_for @client, remote: true do |f| %>

                <% if @client.errors.any? %>
                    <div id="error_explanation">
                    <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

                    <ul>
                    <% @client.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                    </ul>
                    </div>
                <% end %>

                <div class="field">
                    <%= f.label :name %>
                    <%= f.text_field :name %>
                </div>

                <div class="field">
                    <%= f.label :nit %>
                    <%= f.text_field :nit %>
                </div>

                <div class="field">
                    <%= f.label :contact %>
                    <%= f.text_field :contact %>
                </div>

                <div class="field">
                    <%= f.label :address %>
                    <%= f.text_field :address %>
                </div>

                <div class="field">
                    <%= f.label :location %>
                    <%= f.text_field :location %>
                </div>

                <div class="field">
                    <%= f.label :email %>
                    <%= f.text_field :email %>
                </div>

                <div class="field">
                    <%= f.label :phone %>
                    <%= f.text_field :phone %>
                </div>

                <div class="field">
                    <%= f.label :cell_phone %>
                    <%= f.text_field :cell_phone %>
                </div>
               
                <div class="actions">
                    <%= f.submit 'Crear'%>
                </div>
               
            <% end %>

app/views/admin/clients/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_client_path(@admin_client) %> |
<%= link_to 'Back', admin_clients_path %>