config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  namespace :admin do
    resources :products do
      member do
          patch :toggle_enable_status
          patch :search
      end
    end
    resources :clients do
      member do
        patch :search_client
      end
    end
    resources :invoices do
      member do
        patch :search_product_invoice
      end
    end
  end

  get :add_product, to: "invoices#add_product"
  get 'admin' => 'admin/products#index'
  resources :clients
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :products_imports, only: [:new, :create] #Import Excel
  resources :products
  resources :categories
  resources :catalog
  get :generate_pdf, to: "products#generate_pdf"
  root 'welcome#index'
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :clients
  belongs_to :product

  def client_name
    clients.try(:name)
  end

  def client_name=(name)
    self.clients = Client.find_by_name(name) if name.present?
  end
  
end

app/controllers/admin/invoices_controller.rb
class Admin::InvoicesController < ApplicationController
  before_action :set_admin_invoice, only: [:show, :edit, :update, :destroy]


  def index
    @invoices = Invoice.all
  end
  
  def add_product
    respond_to do |f|
      f.html
      f.js 
    end  
  end
  
  def show
  end

  # GET /admin/invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /admin/invoices/1/edit
  def edit
  end

  # POST /admin/invoices
  # POST /admin/invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
        format.js
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/invoices/1
  # PATCH/PUT /admin/invoices/1.json
  def update
    respond_to do |format|
      if @admin_invoice.update(admin_invoice_params)
        format.html { redirect_to @admin_invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_invoice }
      else
        format.html { render :edit }
        format.json { render json: @admin_invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/invoices/1
  # DELETE /admin/invoices/1.json
  def destroy
    @admin_invoice.destroy
    respond_to do |format|
      format.html { redirect_to admin_invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_invoice
      @admin_invoice = Admin::Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_invoice_params
      params.fetch(:admin_invoice, {})
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]


  def index
    @invoices = Invoice.all
  end
 
  def add_product
    @products = Product.where(["name ILIKE ?","%#{params[:search_product_invoice]}%"])
    respond_to do |f|
      f.html
      f.js 
    end 
  end

  
  def show
  end

  def new  
    respond_to do |f|
      f.html
      f.js 
    end  
  end

 
  def edit
  end

  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
        format.js
      else
        format.html { render :show}
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:prefix, :invoice_number, :sub_total, :total, :client_id)
    end
end

app/helpers/admin/invoices_helper.rb
module Admin::InvoicesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_add_product.html.erb
<div id="myModal" class="modal fade" tabindex="-1" style="background-color: rgba(0, 0, 0, 0.9);" data-backdrop="false">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title-centered">Agregar Producto</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <%= form_tag admin_invoices_path, method: :get do %>
                    <div class="form-group">
                        <%= text_field_tag :search_product_invoice, params[:search_product_invoice], class: "form-control", placeholder: "Buscar" %>
                    </div>
                    <%= submit_tag 'Buscar', name: nil, class: "btn btn-primary btn-md" %>
                <% end %>
    
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <div class="actions">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/invoices/_form.html.erb
<div class="container-products">
 <p id="notification"></p>  
    <%= form_for @invoice, local: true do |f| %>

        <div class="row title-products">
            <div class="col-md-6">
                <h2>NUEVA FACTURA</h2>
            </div>  
        </div>
       
        <% if @invoice.errors.any? %>
            <div id="error_explanation">
            <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

            <ul>
            <% invoice.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
            </div>
        <% end %>
    
        <div class="row">
            <div class="col-md-6 field">
                <%= f.label :Prefijo %>
                <%= f.text_field :prefix, class: 'disabled'%>
            </div>

            <div class="col-md-6 field">
                <%= f.label :Número_de_factura %>
                <%= f.number_field :invoice_number %>
            </div>
        </div>
       
        <div class="clients-dropdown">
            <%= f.label :Cliente %>
            <%= f.text_field :client_id, data: {autocomplete_source: Client.order(:name).map(&:name)}, id: 'invoice_client_name' %>
        </div> 

        <div class="row">
            <div class="col-md-12 table-responsive">
                <hr>
                <table class="table table-hover" id="items">
            
                    <thead>
                        <th class="item-name">Producto</th>
                        <th class="description">Descripción</th>
                        <th class="unit">Valor unit</th>
                        <th class="quantity">Cantidad</th>
                        <th class="units">Subtotal</th>
                        <th class="no_print"></th>
                    </thead>
                
                    <tbody>
                        <tr class="item-row">
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row container-button-newproduct"> 
            <div class="col-md-12">
                <%= link_to '<i class="fa fa-plus-circle"></i> Agregar Producto'.html_safe, add_product_path, :remote => true, 'data-toggle' =>  "modal", 'data-target' => 'add_products', class: 'btn-new-product'%>
                <%= f.submit 'Crear Factura', class: 'btn-new-product'%>
            </div>  
        </div>

        <%= form_tag admin_invoices_path, method: :get do %>
            <div class="form-group">
                <%= text_field_tag :search_product_invoice, params[:search_product_invoice], class: "form-control", placeholder: "Buscar" %>
            </div>
            <%= submit_tag 'Buscar', name: nil, class: "btn btn-primary btn-md" %>
        <% end %>
        <div id="add-products" style="display:none;"></div>
    <% end %>
</div>  

app/views/invoices/_new.html.erb
<div class="wrapper">
    <!-- Sidebar Holder -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <%= image_tag("nav/AEI.png", class: "img-responsive", id: "navbar-logo", size: "180x135") %>  
        </div>

        <ul class="list-unstyled components">
            <p class="dashboard">Dashboard</p>
             <li>
                <%= link_to "Inicio", admin_path, class: "text-menu"%>
            </li>
            <li>
                <%= link_to "Productos", admin_path, class: "text-menu"%>
            </li>
            <li>
                <%= link_to "Clientes", admin_clients_path, class: "text-menu"%>        
            </li>
            <li class="active">
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle text-menu">Facturación</a>
                <ul class="collapse list-unstyled" id="homeSubmenu">
                    <li>
                                
                    </li> 
                </ul>
            </li>
            <% if current_user%>
            <li>
                <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "text-menu"%>
            </li> 
            <% end %>
        </ul>
    </nav>

    <!-- Page Content Holder -->
    <div id="content">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="navbar-btn">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-align-justify"></i>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <%= render 'invoices/form' %>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#sidebarCollapse').on('click', function () {
            $('#sidebar').toggleClass('active');
            $(this).toggleClass('active');
        });
    });

    $('#invoice_client_name').autocomplete({
        source: $('#invoice_client_name').data('autocomplete-source')
    });
</script>

app/views/invoices/_view_all.html.erb
<div class="container-products">
  <div class="row title-products">
    <div class="col-md-6">
      <h2>FACTURAS DE VENTA</h2>
    </div>  
    <div class="row container-button-newproduct float-right"> 
      <div class="col-md-12">
        <%= link_to '<i class="fa fa-plus-circle"></i> Nueva Factura'.html_safe, new_admin_invoice_path, class: 'btn-new-product'%>
      </div>  
    </div>
  </div>
  <div class="table-responsive-sm">
    <table class="table">
      <thead class=thead-border>
          <th scope="col">Prefijo</th>
          <th scope="col">No. FV</th>
          <th scope="col">Sub total</th>
          <th scope="col">Total</th>
          <th scope="col">Cliente</th>
        </tr>
      </thead>

      <tbody>
        <% @invoices.each do |invoice| %>
          <tr>
            <td><%= invoice.prefix %></td>
            <td><%= invoice.invoice_number %></td>
            <td><%= invoice.sub_total %></td>
            <td><%= invoice.total %></td>
            <td><%= invoice.client %></td>
            <td><%= link_to '<i class="fa fa-edit edit-product"></i>'.html_safe, edit_invoice_path(invoice) %></td>
            <% if can? :destroy, @invoice %>
              <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>  
          </tr>
        <% end %>
      </tbody>
    </table>

   
    <div id="invoice-new" style="display:none;"></div>
  </div>
</div>

app/views/invoices/add_product.js.erb
$('#add-products').html("<%= j (render 'add_product') %>");
$('#myModal').modal('show')
$('#add-products').slideDown(350)

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<%= render 'view_all' %>

app/views/invoices/new.js.erb
$('#invoice-new').html("<%= j (render 'new') %>");
$('#myModal').modal('show')
$('#invoice-new').slideDown(350)

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prefix:</strong>
  <%= @invoice.prefix %>
</p>

<p>
  <strong>Invoice number:</strong>
  <%= @invoice.invoice_number %>
</p>

<p>
  <strong>Sub total:</strong>
  <%= @invoice.sub_total %>
</p>

<p>
  <strong>Total:</strong>
  <%= @invoice.total %>
</p>

<p>
  <strong>Client:</strong>
  <%= @invoice.clients %>
</p>

<p>
  <strong>Product:</strong>
  <%= @invoice.product %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>