config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  namespace :admin do
    resources :products do
      member do
          patch :toggle_enable_status
          patch :search
      end
    end
    resources :clients do
      member do
        patch :search_client
      end
    end
    resources :invoices do
      member do
        patch :search_product_invoice
      end
    end
  end

  get :add_product, to: "invoices#add_product"
  get 'admin' => 'admin/products#index'
  resources :clients
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :products_imports, only: [:new, :create] #Import Excel
  resources :products
  resources :categories
  resources :catalog
  get :generate_pdf, to: "products#generate_pdf"
  root 'welcome#index'
end

app/models/product.rb
class Product < ApplicationRecord
    has_many_attached :uploads
    has_and_belongs_to_many :categories
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_admin_product, only: [:show, :edit, :update, :destroy]

  # GET /admin/products
  # GET /admin/products.json
  def index
    @products = Product.where(["name ILIKE ?","%#{params[:search]}%"])    
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=productos.xlsx"
      }
      format.html { render :index }
    end
  end


  def toggle_enable_status
    @product.toggle!(:enabled)
  end


  def show
   @products = Product.all
  end

  # GET /admin/products/new
  def new
    @product = Product.new
    respond_to do |f|
      f.html
      f.js 
    end  
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @admin_product = Admin::Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to @admin_product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1
  # PATCH/PUT /admin/products/1.json
  def update
    respond_to do |format|
      if @admin_product.update(admin_product_params)
        format.html { redirect_to @admin_product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_product }
      else
        format.html { render :edit }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @admin_product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Admin::Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_product_params
      params.fetch(:admin_product, {})
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def generate_pdf
    respond_to do |format|
      format.html
      format.pdf do
        render  pdf: "Factura",
             template: 'products/generate_pdf.pdf.erb',
             page_size: 'Letter',
             zoom: 1,
             background: true,
             margin: {
               top: 0,
               bottom:0,
               left:0,
               right:0 
        }
      end
    end
  end
  

  def index
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=productos.xlsx"
      }
      format.html { render :index }
    end
  end
 
  def show
    @products = Product.all
  end
  

  # GET /products/new
  def new
    @product = Product.new
    respond_to do |f|
      f.html
      f.js 
    end  
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :sale_price, :purchase_price, :sku, :stock, :state, uploads: [])
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: admin_product, local: true) do |form| %>
  <% if admin_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
      <% admin_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/products/_new.html.erb
<div id="myModal" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title-centered">Nuevo Producto</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for @product, remote: true do |f| %>
            <% if @product.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

                    <ul>
                    <% product.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="field">
                <%= f.label :Nombre %>
                <%= f.text_field :name %>
            </div>

            <div class="field">
                <%= f.label :Descripción %>
                <%= f.text_area :description %>
            </div>

            <div class="field">
                <%= f.label :Precio_de_compra %>
                <%= f.number_field :purchase_price %>
            </div>
            
            <div class="field">
                <%= f.label :Precio_de_venta %>
                <%= f.number_field :sale_price %>
            </div>

            <div class="field">
                <%= f.label :SKU %>
                <%= f.text_field :sku %>
            </div>

            <div class="field">
                <%= f.label :Stock %>
                <%= f.number_field :stock %>
            </div>

            <div class="field">
                <%= f.label :Estado %>
                <%= f.check_box :state %>
            </div>

            <%= f.label :uploads%>
            <%= f.file_field :uploads, multiple: true%>

            <div class="departments-dropdown">
                <%= f.collection_select(:category_ids, Category.all, :id, :name, { include_blank: "Categoría"},  {class: "btn btn-default dropdown-toggle"}) %>
            </div> 
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <div class="actions">
                    <%= f.submit 'Crear'%>
                </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/_products.html.erb
<div class="wrapper">
    <!-- Sidebar Holder -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <%= image_tag("nav/AEI.png", class: "img-responsive", id: "navbar-logo", size: "180x135") %>  
        </div>

        <ul class="list-unstyled components">
            <p class="dashboard">Dashboard</p>
            <li class="active">
                <%= link_to "Clientes", admin_clients_path, class: "text-menu"%>
            </li>
             <li class="active">
                <%= link_to "Productos", admin_products_path, class: "text-menu"%>
            </li>
            <li>
                <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "text-menu"%>
            </li> 
        </ul>
    </nav>

    <!-- Page Content Holder -->
    <div id="content">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="navbar-btn">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-align-justify"></i>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <%= render 'products/view_products'%>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#sidebarCollapse').on('click', function () {
            $('#sidebar').toggleClass('active');
            $(this).toggleClass('active');
        });
    });
</script>

app/views/admin/products/_sidebar.html.erb
<div class="wrapper">
    <!-- Sidebar Holder -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <%= image_tag("nav/AEI.png", class: "img-responsive", id: "navbar-logo", size: "180x135") %>  
        </div>

        <ul class="list-unstyled components">
            <p class="dashboard">Dashboard</p>
             <li>
                <%= link_to "Inicio", admin_clients_path, class: "text-menu"%>               
            </li>
            <li>
                <%= link_to "Productos", admin_path, class: "text-menu"%>
            </li>
            <li>
                <%= link_to "Clientes", admin_clients_path, class: "text-menu"%>        
            </li>
            <li class="active">
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle text-menu">Facturación</a>
                <ul class="collapse list-unstyled" id="homeSubmenu">
                    <li>
                        <%= link_to "Facturas de Venta", admin_invoices_path, class: "text-menu"%>        
                    </li> 
                </ul>
            </li>
            <% if current_user%>
            <li>
                <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "text-menu"%>
            </li> 
            <% end %>
        </ul>
    </nav>

    <!-- Page Content Holder -->
    <div id="content">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="navbar-btn">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-align-justify"></i>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Page</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <%= render 'products/view'%>

</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#sidebarCollapse').on('click', function () {
            $('#sidebar').toggleClass('active');
            $(this).toggleClass('active');
        });
    });
</script>

app/views/admin/products/edit.html.erb
<h1>Editing Admin Product</h1>

<%= render 'form', admin_product: @admin_product %>

<%= link_to 'Show', @admin_product %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/new.js.erb
$('#product-new').html("<%= j (render 'new') %>");
$('#myModal').modal('show')
$('#product-new').slideDown(360)

app/views/admin/products/new1.html.erb
<h1>New Admin Product</h1>

<%= render 'form', admin_product: @admin_product %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_product_path(@admin_product) %> |
<%= link_to 'Back', admin_products_path %>