config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  namespace :admin do
    resources :products do
      member do
          patch :toggle_enable_status
          patch :search
      end
    end
    resources :clients do
      member do
        patch :search_client
      end
    end
    resources :invoices do
      member do
        patch :search_product_invoice
      end
    end
  end

  get :add_product, to: "invoices#add_product"
  get 'admin' => 'admin/products#index'
  resources :clients
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :products_imports, only: [:new, :create] #Import Excel
  resources :products
  resources :categories
  resources :catalog
  get :generate_pdf, to: "products#generate_pdf"
  root 'welcome#index'
end

app/models/product.rb
class Product < ApplicationRecord
    has_many_attached :uploads
    has_and_belongs_to_many :categories
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_admin_product, only: [:show, :edit, :update, :destroy]

  # GET /admin/products
  # GET /admin/products.json
  def index
    @products = Product.where(["name ILIKE ?","%#{params[:search]}%"])    
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=productos.xlsx"
      }
      format.html { render :index }
    end
  end


  def toggle_enable_status
    @product.toggle!(:enabled)
  end


  def show
   @products = Product.all
  end

  # GET /admin/products/new
  def new
    @product = Product.new
    respond_to do |f|
      f.html
      f.js 
    end  
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @admin_product = Admin::Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to @admin_product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1
  # PATCH/PUT /admin/products/1.json
  def update
    respond_to do |format|
      if @admin_product.update(admin_product_params)
        format.html { redirect_to @admin_product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_product }
      else
        format.html { render :edit }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @admin_product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Admin::Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_product_params
      params.fetch(:admin_product, {})
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def generate_pdf
    respond_to do |format|
      format.html
      format.pdf do
        render  pdf: "Factura",
             template: 'products/generate_pdf.pdf.erb',
             page_size: 'Letter',
             zoom: 1,
             background: true,
             margin: {
               top: 0,
               bottom:0,
               left:0,
               right:0 
        }
      end
    end
  end
  

  def index
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=productos.xlsx"
      }
      format.html { render :index }
    end
  end
 
  def show
    @products = Product.all
  end
  

  # GET /products/new
  def new
    @product = Product.new
    respond_to do |f|
      f.html
      f.js 
    end  
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :sale_price, :purchase_price, :sku, :stock, :state, uploads: [])
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Descripción %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :Precio_de_compra %>
    <%= form.number_field :purchase_price %>
  </div>
  
  <div class="field">
    <%= form.label :Precio_de_venta %>
    <%= form.number_field :sale_price %>
  </div>

  <div class="field">
    <%= form.label :SKU %>
    <%= form.text_field :sku %>
  </div>

  <div class="field">
    <%= form.label :Stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="field">
    <%= form.label :Estado %>
    <%= form.check_box :state %>
  </div>

  <%= form.label :uploads%>
  <%= form.file_field :uploads, multiple: true%>

  <div class="departments-dropdown">
      <%= form.collection_select(:category_ids, Category.all, :id, :name, { include_blank: "Categoría"},  {class: "btn btn-default dropdown-toggle"}) %>
  </div> 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_new.html.erb
<div id="myModal" class="modal fade" tabindex="-1" style="background-color: rgba(0, 0, 0, 0.9);" data-backdrop="false">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title-centered">Nuevo Producto</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for @product, remote: true do |f| %>
            <% if @product.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

                    <ul>
                    <% product.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="field">
                <%= f.label :Nombre %>
                <%= f.text_field :name %>
            </div>

            <div class="field">
                <%= f.label :Descripción %>
                <%= f.text_area :description %>
            </div>

            <div class="field">
                <%= f.label :Precio_de_compra %>
                <%= f.number_field :purchase_price %>
            </div>
            
            <div class="field">
                <%= f.label :Precio_de_venta %>
                <%= f.number_field :sale_price %>
            </div>

            <div class="field">
                <%= f.label :SKU %>
                <%= f.text_field :sku %>
            </div>

            <div class="field">
                <%= f.label :Stock %>
                <%= f.number_field :stock %>
            </div>

            <div class="field">
                <%= f.label :Estado %>
                <%= f.check_box :state %>
            </div>

            <%= f.label :uploads%>
            <%= f.file_field :uploads, multiple: true%>

            <div class="departments-dropdown">
                <%= f.collection_select(:category_ids, Category.all, :id, :name, { include_blank: "Categoría"},  {class: "btn btn-default dropdown-toggle"}) %>
            </div> 
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <div class="actions">
                    <%= f.submit 'Crear', remote: true%>
                </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/_view.html.erb
<div class="container-products">
  <div class="row title-products">
    <div class="col-md-6">
      <h2>PRODUCTOS</h2>
    </div>  
  </div> 

  <div class="row ">
    <div class=col-md-4> 
      <%= form_tag admin_products_path, method: :get do %>
            <div class="row">
              <div class="col-md-12">
                <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Busca productos por nombre" %>
                <%= submit_tag 'Buscar', name: nil, class: "btn btn-primary btn-md" %>
              </div>
            </div>  
      <% end %>
    </div>  
    <div class="col-md-4">
      <!--<%= link_to 'Cargar Excel',new_products_import_path %>-->
      <%= link_to '<i class="fas fa-file-download"></i> Descargar Excel'.html_safe,admin_products_path(format: :xlsx), class: 'btn-excel'%>
      <!--<%= link_to '<i class="fas fa-file-download"></i> Generar PDF'.html_safe, generate_pdf_path(format: :pdf), class: 'btn-generate-pdf' %>-->
      <%= link_to '<i class="fa fa-plus-circle"></i> Nuevo Producto'.html_safe, new_product_path, :remote => true, 'data-toggle' =>  "modal", 'data-target' => 'product-new', class: 'btn-new-product'%>
    </div>  
  </div>

  <div class="table-responsive-sm">
    <table class="table">
      <thead class=thead-border>
        <tr>
          <th scope="col">Estado</th>
          <th scope="col">Stock</th>
          <th scope="col">Nombre</th>
          <th scope="col">Descripción</th>
          <th scope="col">SKU</th>
          <th scope="col">Precio de Compra</th>
          <th scope="col">Precio de venta</th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td class="product-<%= product.state %>">
                <%= link_to "#{ product.state ? '' : '' }", toggle_enable_status_admin_product_path(product), method: :patch, remote: :true, class: "btn btn-xs btn-#{ product.state ? 'success' : 'danger' }"%>
            </td>
            <td><%= product.stock %></td>
            <td><%= product.name %></td>
            <td><%= product.description %></td>
            <td><%= product.sku %></td>
            <td><%= product.purchase_price %></td>
            <td><%= product.sale_price %></td>
            <td><%= link_to '<i class="fa fa-edit edit-product"></i>'.html_safe, edit_product_path(product) %></td>
            <% if can? :destroy, @product %>
              <td><%= link_to '<i class="fa fa-trash delete-product"></i>'.html_safe, product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
     <div id="product-new" style="display:none;"></div>
  </div>
</div>

app/views/products/_view_all.html.erb
<div class="container-products">
  <div class="row title-products">
    <div class="col-md-12">
      <h2>Productos</h2>
    </div>  
  </div> 
  <div class="row container-button-newproduct float-right"> 
    <div class="col-md-12">
      <%= link_to 'Descargar Excel',products_path(format: :xlsx)%>
      <%= link_to 'Cargar Excel',new_products_import_path %>
      <%= link_to '<i class="fas fa-file-download"></i> Generar PDF'.html_safe, generate_pdf_path(format: :pdf), class: 'btn-generate-pdf' %>
      <%= link_to '<i class="fa fa-plus-circle"></i> Nuevo Producto'.html_safe, new_product_path,:remote => true, 'data-toggle' =>  "modal", 'data-target' => 'product-new', class: 'btn-new-product'%>
    </div>  
  </div>
 
  </div>
  <div class="table-responsive-sm">
    <table class="table">
      <thead class=thead-border>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Descripción</th>
          <th scope="col">Precio de Compra</th>
          <th scope="col">Nombre</th>
          <th scope="col">Precio de venta</th>
          <th scope="col">SKU</th>
          <th scope="col">Estado</th>
          <th scope="col">Stock</th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= product.description %></td>
            <td><%= product.purchase_price %></td>
            <td><%= product.name %></td>
            <td><%= product.sale_price %></td>
            <td><%= product.sku %></td>
            <td><%= product.state %></td>
            <td><%= product.stock %></td>
            <td><%= link_to '<i class="fa fa-edit edit-product"></i>'.html_safe, edit_product_path(product) %></td>
            <% if can? :destroy, @product %>
              <td><%= link_to '<i class="fa fa-trash delete-product"></i>'.html_safe, product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
     <div id="product-new" style="display:none;"></div>
  </div>
</div>

app/views/products/_view_products.html.erb
<div class="container-products">
  <div class="row title-products">
    <div class="col-md-6">
      <h1>Productos</h1>
    </div>  
  </div> 
  <div class="row container-button-newproduct float-right"> 
    <div class="col-md-12">
      <%= link_to 'Cargar Excel',new_products_import_path %>
      <%= link_to '<i class="fas fa-file-download"></i> Descargar Excel'.html_safe,products_path(format: :xlsx), class: 'btn-excel'%>
      <!--<%= link_to '<i class="fas fa-file-download"></i> Generar PDF'.html_safe, generate_pdf_path(format: :pdf), class: 'btn-generate-pdf' %>-->
      <%= link_to '<i class="fa fa-plus-circle"></i> Nuevo Producto'.html_safe, new_product_path,:remote => true, 'data-toggle' =>  "modal", 'data-target' => 'product-new', class: 'btn-new-product'%>
    </div>  
  </div>

  <div class="table-responsive-sm">
    <table class="table">
      <thead class=thead-border>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Descripción</th>
          <th scope="col">Precio de Compra</th>
          <th scope="col">Nombre</th>
          <th scope="col">Precio de venta</th>
          <th scope="col">SKU</th>
          <th scope="col">Estado</th>
          <th scope="col">Stock</th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= product.description %></td>
            <td><%= product.purchase_price %></td>
            <td><%= product.name %></td>
            <td><%= product.sale_price %></td>
            <td><%= product.sku %></td>
            <td><%= product.state %></td>
            <td><%= product.stock %></td>
            <td><%= link_to '<i class="fa fa-edit edit-product"></i>'.html_safe, edit_product_path(product) %></td>
            <% if can? :destroy, @product %>
              <td><%= link_to '<i class="fa fa-trash delete-product"></i>'.html_safe, product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
     <div id="product-new" style="display:none;"></div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/generate_pdf.pdf.erb
<p>Soy un PDF</p>

app/views/products/index.html.erb
<%= render 'view'%>

app/views/products/new.js.erb
$('#product-new').html("<%= escape_javascript render('new') %>");
$('#myModal').modal('show')
$('#product-new').slideDown(10)

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<div>
  <% @product.uploads.each do |upload|%>
    <% if upload.variable? %>
      <%= link_to image_tag(upload.variant(resize: "400x400")), upload %>
    <% elsif upload.previemable? %>
      <%= link_to image_tag(upload.preview(resize: "400x400")), rails_blob_path(upload, disposition: :attachment)%>
    <% elsif upload.image? %>
      <%= link_to image_tag(upload, width: 400), upload%>
    <% else %>   
      <%= link_to upload.filename, rails_blob_path(upload, disposition: :attachment)%> 
    <% end %> 
  <% end %>
</div>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/toggle_enabled_status.js.erb
<% if @product.state == true %>
    $(".product-<%= @product.id %> > a").html('').removeClass('btn-warning').addClass('btn-success')
<% else %>
    $(".product-<%= @product.id %> > a").html('').removeClass('btn-success').addClass('btn-warning')
<% end %>
$("#product-status-<%= @product.id %>").html()